version: 2

sources:
  - name: staging
    database: ny-rides-sulman 
     # For postgres:
      #database: production
    schema: taxi_data

      # loaded_at_field: record_loaded_at
    tables:
      - name: external_table_green_taxi_data 
      - name: external_table_yellow_taxi_data 
         # freshness:
           # error_after: {count: 6, period: hour}

